# Generated by Django 4.0.4 on 2022-05-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_alter_extrainfo_celiac_alter_extrainfo_child_seat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
