# Generated by Django 4.0.4 on 2022-05-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0008_alter_dish_category_alter_dish_name_alter_dish_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(null=True, verbose_name='Notatki'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('Przystawka', 'Przystawka'), ('Przystawka grupowa', 'Przystawka grupowa'), ('Zupa', 'Zupa'), ('Danie główne', 'Danie główne'), ('Deser', 'Deser')], max_length=32, verbose_name='Kategoria'),
        ),
    ]
