# Generated by Django 4.0.4 on 2022-05-18 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0009_reservation_notes_alter_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='celiac',
            field=models.PositiveIntegerField(default=0, verbose_name='Celiakia'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='child_seat',
            field=models.PositiveIntegerField(default=0, verbose_name='Krzesełko dla dziecka'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='dairy',
            field=models.PositiveIntegerField(default=0, verbose_name='Dieta beznabiałowa'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='peanut_allergy',
            field=models.PositiveIntegerField(default=0, verbose_name='Alergia na orzechy'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='vegan',
            field=models.PositiveIntegerField(default=0, verbose_name='Dieta wegańska'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='vegetarian',
            field=models.PositiveIntegerField(default=0, verbose_name='Dieta wegetariańska'),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='extra_info',
        ),
        migrations.AddField(
            model_name='reservation',
            name='extra_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_app.extrainfo', verbose_name='Dodatkowe informacje'),
        ),
        migrations.DeleteModel(
            name='ReservationExtraInfo',
        ),
    ]
