# Generated by Django 4.0.4 on 2022-05-18 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0011_alter_reservation_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='reservation_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager_app.reservation', verbose_name='Rezerwacja'),
            preserve_default=False,
        ),
    ]
