# Generated by Django 4.0.4 on 2022-05-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0012_extrainfo_reservation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrainfo',
            name='reservation_id',
        ),
    ]
