# Generated by Django 4.0.4 on 2022-05-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0015_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_hour',
            field=models.TimeField(choices=[], null=True, verbose_name='Godzina zakończenia'),
        ),
    ]
