# Generated by Django 4.0.4 on 2022-05-10 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_reservation_time_alter_reservation_date_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date_hour',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='time',
            new_name='hour',
        ),
    ]
