# Generated by Django 4.0.4 on 2022-05-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0007_alter_reservation_created_alter_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('Przystawka', 'Przystawka'), ('Zupa', 'Zupa'), ('Danie główne', 'Danie główne'), ('Deser', 'Deser')], max_length=32, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nazwa Dania'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='celiac',
            field=models.BooleanField(default=False, verbose_name='Celiakia'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='child_seat',
            field=models.BooleanField(default=False, verbose_name='Krzesełko dla dziecka'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='dairy',
            field=models.BooleanField(default=False, verbose_name='Dieta beznabiałowa'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='peanut_allergy',
            field=models.BooleanField(default=False, verbose_name='Alergia na orzechy'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='vegan',
            field=models.BooleanField(default=False, verbose_name='Dieta wegańska'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='vegetarian',
            field=models.BooleanField(default=False, verbose_name='Dieta wegetariańska'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dishes',
            field=models.ManyToManyField(to='manager_app.dish', verbose_name='Dania'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Nazwa Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.FloatField(verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='reservationextrainfo',
            name='amount',
            field=models.IntegerField(verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(verbose_name='Ilość miejsc'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Stół'),
        ),
    ]
