# Generated by Django 4.0.4 on 2022-05-21 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0013_remove_extrainfo_reservation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrainfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='extra_info',
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='reservation',
            field=models.OneToOneField(default=1810, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='manager_app.reservation', verbose_name='Rezerwacja'),
            preserve_default=False,
        ),
    ]
