# Generated by Django 4.0.4 on 2022-05-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0014_remove_extrainfo_id_remove_reservation_extra_info_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'hour', 'table')},
        ),
    ]
