# Generated by Django 4.0.4 on 2023-07-08 16:28

from django.db import migrations, models
import django.db.models.deletion
import manager_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0020_reservation_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(default=manager_app.models.Restaurant.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_app.restaurant'),
        ),
    ]
