# Generated by Django 4.0.4 on 2023-07-08 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0022_dish_restaurant_menu_restaurant_table_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_hour',
            field=models.TimeField(blank=True, choices=[], null=True, verbose_name='Godzina zakończenia'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_app.menu', verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notatki'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_app.table', verbose_name='Stół'),
        ),
    ]
